### ISSUE TITLE
Doesn't generate type properly when using lookup type

### ISSUE THREAD

**Issue by Dambre** [toanvc/typescript-constructor-generator#1]
First of all, nice job! It does almost everything I need, buuuut it doesn't generate when type is a reference from other class property. 
```
class A {
  woo: string;
}
class B {
 boo: A['woo']
 constructor(boo: A[,) { // <<----- This is how it generates;
   this.boo = boo;
  }
}

```

It seems that it is escaping too early..

**Comment by toanvc** [comment]
Hi, sorry for a very long wait. I didn't have time to update it. The new version should fix your problem. Please update it or install a new one v0.2.0. Thank you!!
