### ISSUE TITLE
Private properties lose #

### ISSUE THREAD

**Issue by Deathrage** [toanvc/typescript-constructor-generator#4]
Class
```
class Test {
   #dependency: Dependency;
}
```
will recieve constructor
```
class Test {
   constructor(dependency: Dependency) {
      this.dependency = dependency;
   }

   #dependency: Dependency;
}
```
.

This constructor assignes property that does not exist.

**Comment by toanvc** [comment]
Hi, sorry for a very long wait. I didn't have time to update it. The new version should fix your problem. Please update it or install a new one v0.2.0. Thank you!!
