### ISSUE TITLE
Arguments on the constructor inherit the ; (semi-colon) from the properties

### ISSUE THREAD

**Issue by iangregsondev** [toanvc/typescript-constructor-generator#6]
Hi,

Great plugin. I noticed 1 issue.

When I generate the constructor, I get the ; (semi-colon) included on the argument line i.e.

```
export class ApiKeyAccount {
  key: ApiKey;
  accountName: string;
  accountUuid: string;
  constructor(key: ApiKey;, accountName: string;, accountUuid: string;) {
    this.key = key
    this.accountName = accountName
    this.accountUuid = accountUuid
  }  
}
```

![image](https://user-images.githubusercontent.com/2370364/207861381-c2829998-8cfa-401a-8590-293482161b5a.png)

**Comment by Nova1545** [comment]
I made a very hacky fix here: [https://github.com/Nova1545/typescript-constructor-generator](https://github.com/Nova1545/typescript-constructor-generator)

You'll have to build the extension yourself, but it atleast it works

**Comment by frarm** [comment]
@Nova1545 It works, thanks

**Comment by d1820** [comment]
I have forked and published a fixed version. since this seems abandoned
https://marketplace.visualstudio.com/items?itemName=DanTurco.danturco-typescript-generate-ctor

**Comment by toanvc** [comment]
Hi @iangregsondev  , I've updated and have a new version to fix this issue. Please update the extension to latest version. Thank you very much!
