### ISSUE TITLE
semicolon is considered as part of the attribute type

### ISSUE THREAD

**Issue by bdridi** [toanvc/typescript-constructor-generator#8]
The semicolon after each attribute declaration is not ignored when the constructor is generated. 
Example : 
```typescript
class City{
    code: string;
    postCode: number;   
  }
```
=> The generated constructor is the following : 
```typescript
constructor(
  code:string;,
  postCode: number;
) {
     this.code = code
     this.postCode = postCode
  }
``` 

Thank you

**Comment by d1820** [comment]
I have forked and published a fixed version. since this seems abandoned
https://marketplace.visualstudio.com/items?itemName=DanTurco.danturco-typescript-generate-ctor

**Comment by toanvc** [comment]
Hi @bdridi , I've updated and have a new version to fix this issue. Please update the extension to latest version. Thank you very much!
